steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/itcarolina/site', '.']
images:
- 'gcr.io/itcarolina/site'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/itcarolina/serviceAccounts/135690989088-compute@developer.gserviceaccount.com'
